name: Build and Publish Docker

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'lighttpd version'
        required: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: lighttpd
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args:
            - "VERSION=${{ inputs.version }}"
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ inputs.version }}
